### ISSUE TITLE
change the bios volume size

### ISSUE THREAD

**Issue by tonno2** [LongSoft/UEFITool#100]
I managed to put my 64mb bios on a 128mb eeprom I would need to change the size of a volume, is it possible?
Thank you
translated with google I do not speak English

**Comment by skochinsky** [comment]
You will  probably need to edit the flash descriptor so that it has correct pointers to the regions (ME/GbE/BIOS). Use the [ifdtool](https://review.coreboot.org/cgit/coreboot.git/tree/util/ifdtool) to manipulate it. Note that you will probably need to update the VSCC table and other flash chip-related parameters (not supported by ifdtool).

**Comment by tonno2** [comment]
thanks, but this program is for linux or with what program I can use it is not for windows.
thank you

**Comment by NikolajSchlej** [comment]
It's possible but difficult and the success of the operation depends heavily on firmware vendor and version. [Here](https://forums.mydigitallife.net/threads/can-i-use-a-larger-capacity-bios-chip-than-the-original-that-came-with-my-motherboard.33818/#post-866356) I've answered a similar question long ago, that answer is still true for now.

**Comment by tonno2** [comment]
But you can not add this option in Uefitool. Thanks
