### ISSUE TITLE
3 times StdDefaults in image

### ISSUE THREAD

**Issue by c0d3z3r0** [LongSoft/UEFITool#115]
In my UEFI image from Lenovo [1] I found the StdDefaults three times at different places:
- in NVRAM
- compressed in "Defaults" / "NVRAM external defaults" (9221315B-30BB-46B5-813E-1B1BF4712BD3)
- in raw file 77D3DC50-D42B-4916-AC80-8F469035D150

All sections have the same content (... ok... the last is missing GUID store).

When I FF'ed the section in NVRAM the UEFI seems to copy one of the other two to the NVRAM section...

My questions:
What does "external" mean here?
Why are there three sections with the same content? o.O

**Comment by NikolajSchlej** [comment]
1. External here means "not stored in NVRAM volume", the name is how AMI calls it.
2. Because AMI really want to make sure that EFI can restore defaults NVRAM contents in any possible corruption case and then continue to boot.

Because it's not an issue in UEFITool or companion tools, I'll close it. You can still continue discussion here, if you want.
