### ISSUE TITLE
Trying to understand and correct this error (if possible): parseBios: one of volumes inside overlaps the end of data

### ISSUE THREAD

**Issue by Phoenix48** [LongSoft/UEFITool#117]
I am trying to understand why i get this error in my Bios, if it is normal and if it is possible to correct it. If yes, how do i do it?

This error comes only for one raw file in the bios. All others raw file have no error. This error is also in the original bios from Asus.

[This is the Bios.](https://mega.nz/#!LEMgBZha!dT9-kh--dfiUFUHAgQ0XpvEKsak4JC-4s2BbYn6rV9o)

**Comment by NikolajSchlej** [comment]
You don't need to correct it. That RAW file has a volume header inside, which is then used by the firmware in case header recovery is needed for some reason. But the RAW file itself is too small to fit that volume, and that's why UEFITool reports it.
Please ignore this message, nothing needs to be done here.
