### ISSUE TITLE
IFWI 2.0 BIOS

### ISSUE THREAD

**Issue by PaulNevada** [LongSoft/UEFITool#260]
Can A59 be used for opening the file to save the rom (version) only? I want to use it later to rollback my laptop's firmware...

**Comment by NikolajSchlej** [comment]
Yes, but that's not a good way to perform a rollback, because all individual board data that were present in the original image will be lost if you flash that "ROM" image somehow.
You can try using a compatible version of Intel Flash Programming Tool, or a hardware SPI flashing device to save and restore a full backup of SPI flash on your laptop.

**Comment by PaulNevada** [comment]
Do you mean I could receive a brick this way? And if I will rollback so and then update the regular way with on of the next official file - won't all the potential lost bios data come back to its origianl place?

**Comment by NikolajSchlej** [comment]
IDK about bricking, but you could loose your board data this way. A factory update file, even extracted from it's Capsule, is not a full backup, because it lacks the individual board data. A better backup would be an image of your current BIOS made using Intel FPT or HW flash programmer.

**Comment by PaulNevada** [comment]
Not an update file, but a 8MB-in-size file. Isn't it a full one?

**Comment by PaulNevada** [comment]
What is that "individual board data"?

**Comment by NikolajSchlej** [comment]
Individual board data is motherboard serial number, motherboard UUID and some other things.
<img width="285" alt="Screen Shot 2022-03-28 at 18 03 23" src="https://user-images.githubusercontent.com/1845688/160439907-cfe22595-4ab5-4a0a-a231-b87b5a92432b.png">

**Comment by PaulNevada** [comment]
Thanks for the given info!
