### ISSUE TITLE
Segfault while loading firmware for Lenovo Yoga 7

### ISSUE THREAD

**Issue by stuarthayhurst** [LongSoft/UEFITool#338]
I've extracted the UEFI firmware, with innoextract and InsydeImageExtractor, but this tool gives a segfault while trying to load it.

I've uploaded the file for troubleshooting:
[out.zip](https://github.com/LongSoft/UEFITool/files/10583449/out.zip)

**Comment by NikolajSchlej** [comment]
<img width="1036" alt="Screenshot 2023-02-03 at 16 12 14" src="https://user-images.githubusercontent.com/1845688/216733602-107f60e9-4148-4a13-b618-868273f9a3dd.png">
Did not segfaulted for me. Could you share the more information on the OS and tool versions, so we can reproduce it?

**Comment by stuarthayhurst** [comment]
Hm, I'm on an up-to-date Debian Sid (`uefitool` version `0.28.0+A62-1`), but it also happened with the current flatpak version

**Comment by NikolajSchlej** [comment]
Confirmed the crash of the latest flatpak build on Fedora 37, investigating.

**Comment by NikolajSchlej** [comment]
Same crash as #336, should be fixed by the ToT commit. You can download the artifact from Github Actions for this repo or wait for a new release.

> Thread 1 "uefitool" received signal SIGSEGV, Segmentation fault.
0x00007ffff6848c99 in QtPrivate::qustrlen(char16_t const*) () from /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
(gdb) bt
#0  0x00007ffff6848c99 in QtPrivate::qustrlen(char16_t const*) () at /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#1  0x00007ffff68588e8 in QString::fromUtf16(char16_t const*, long long) () at /usr/lib/x86_64-linux-gnu/libQt6Core.so.6
#2  0x0000555555591aa9 in NvramParser::parseVssStoreBody(QModelIndex const&, unsigned char) ()

**Comment by NikolajSchlej** [comment]
This is the link to that artifact, need to be logged in to GitHub to download it: https://github.com/LongSoft/UEFITool/suites/10703275646/artifacts/536038575

**Comment by stuarthayhurst** [comment]
Thank you
