### ISSUE TITLE
UEFITool enhancement proposals

### ISSUE THREAD

**Issue by NikolajSchlej** [LongSoft/UEFITool#9]
- [ ] UI for section/file/volume creation
- [x] Embedded hex viewer/editor
- [ ] Plugins and/or scripting support
- [ ] Command-line interface
- [ ] Log of applied changes (both before and after rebuild)
- [ ] Undo/redo capability

**Comment by johnrandomsmith2** [comment]
The benefit of diffing in your tool would be that you could add a whitelist for wherever the UEFI non-volatile variables show up in different vendors' BIOSes, so that they could be ignored as false positives.

But if you're recommending folder-level diffing, then I would ask that once you add non-volatile variable parsing, that you put them into files in such a way that they can still be diffed with a folder-level diffing.

**Comment by johnrandomsmith2** [comment]
I also thought of another nice-to-have improvement: file name filtering! So if I put in "SMM" it will show only those files that have SMM in their name (maybe with a little check box for case sensitive vs. insensitive.)

**Comment by NikolajSchlej** [comment]
So basically I need to implement NVRAM parsing as another type of FFS, I think, and it will automatically be dumped by UEFIExtract. Will think about it after adding FIT support, just have no time for it right now.
UI must be reworked to add any filtering, but I will think about it too.
Thank you for your feedback, it's really helpful.

**Comment by johnrandomsmith2** [comment]
Thought of another one:
It would be nice to list the file offset for a selected file (assuming it's uncompressed in the flash dump). So for instance if I click on a PEIM, it could show me the file offset, so I could then slap the overall file into a hex editor and go to some offset from there and just modify some bytes. I know that's what UEFIPatch is supposed to do, but I have a situation where UEFIPatch won't work due to duplicate GUIDs.

**Comment by NikolajSchlej** [comment]
Will be done in the next major release. I'm rewriting the ffsEngine to move from recursive parsing to iterative one, and file offsets will be added to all uncompressed items as a part of new parsing process.

**Comment by NikolajSchlej** [comment]
I'm rewriting the engine from scratch right now, and parser part is almost done. A testing binary for Windows can be obtained [here](https://www.dropbox.com/s/617n80izsfsefpu/UEFITool_parser_only.7z?dl=0), sources will be released a bit later as a separate development branch.
Some of proposals like offsets, FFSv3 support, better handling of malformed elements, names for extracted data and other small things are alredy implemented.

**Comment by vit9696** [comment]
Ideally the code is submitted to extend existing UEFeplace interface =) We are a bit short on hands.

**Comment by NikolajSchlej** [comment]
Better to have separate issues for every proposal, closing.
